name: frontend_geolocation
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5 
  get_it: ^7.6.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3 
  provider: ^6.1.2
  dio: ^5.3.4
  pretty_dio_logger: ^1.3.2
  flutter_lints: ^5.0.0 
  dio_http2_adapter: ^2.3.2 
  

dev_dependencies:
  flutter_lints: ^5.0.0


flutter:  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: FontPoppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

